# Generated by Django 3.2.7 on 2021-09-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='uploads/video')),
                ('details', models.TextField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('original_price', models.PositiveIntegerField(max_length=12)),
                ('discount_price', models.PositiveIntegerField(max_length=12)),
                ('product_details', models.TextField(max_length=300)),
                ('stock', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('feet', 'feet'), ('kg', 'kg'), ('pcs', 'pcs')], max_length=10)),
                ('photo', models.ImageField(upload_to='uploads/product')),
                ('status', models.BooleanField(default=True)),
                ('featured', models.BooleanField()),
                ('best_seller', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default=None, max_length=255, null=True)),
                ('last_name', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('session_token', models.CharField(default=0, max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='uploads/user')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
