# Generated by Django 3.2.7 on 2021-09-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='uploads/video')),
                ('details', models.TextField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('original_price', models.PositiveIntegerField(max_length=12)),
                ('discount_price', models.PositiveIntegerField(max_length=12)),
                ('product_details', models.TextField(max_length=300)),
                ('stock', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('feet', 'feet'), ('kg', 'kg'), ('pcs', 'pcs')], max_length=10)),
                ('photo', models.ImageField(upload_to='uploads/product')),
                ('status', models.BooleanField(default=True)),
                ('featured', models.BooleanField()),
                ('best_seller', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironapp.category')),
            ],
        ),
    ]
