# Generated by Django 3.2.7 on 2021-09-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironapp', '0004_billinginfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
